In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

torch.manual_seed(1)

# 1. Simple linear regression

In [3]:
# train data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [4]:
# initialize the model using nn module
model = nn.Linear(1,1)   # simple linear regression, input_dim = 1, output_dim = 1

In [5]:
# check the parameters of the model
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [6]:
# initiate the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)  # SGD, learning rate=0.01

In [7]:
# train the model
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  # H(x)
  prediction = model(x_train)

  # cost
  cost = F.mse_loss(prediction, y_train)  # mse

  optimizer.zero_grad() # initialize gradient to 0
  cost.backward()       # backward calculation
  optimizer.step()      # update weight and bias

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [8]:
# test the model with a random input of 4
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)               # forward calculation
print('prediction when input = 4:', pred_y)

prediction when input = 4: tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [9]:
# check the parameters of the model
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


# 2. Multiple linear regression

In [25]:
torch.manual_seed(1)

# train data
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [26]:
# initialize the model using nn module
model = nn.Linear(3,1)   # multiple linear regression, input_dim = 3, output_dim = 1

In [27]:
# check the parameters of the model
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [28]:
# initiate the optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)  # SGD, learning rate=0.01

In [29]:
# train the model
nb_epochs = 2000
for epoch in range(nb_epochs+1):

  # H(x)
  prediction = model(x_train)
  # model(x_train) is equivalent to model.forward(x_train)

  # cost
  cost = F.mse_loss(prediction, y_train)  # mse

  optimizer.zero_grad() # initialize gradient to 0
  cost.backward()       # backward calculation
  optimizer.step()      # update weight and bias

  if epoch % 100 == 0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225993
Epoch  200/2000 Cost: 0.223911
Epoch  300/2000 Cost: 0.221941
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218271
Epoch  600/2000 Cost: 0.216575
Epoch  700/2000 Cost: 0.214950
Epoch  800/2000 Cost: 0.213413
Epoch  900/2000 Cost: 0.211952
Epoch 1000/2000 Cost: 0.210560
Epoch 1100/2000 Cost: 0.209232
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206761
Epoch 1400/2000 Cost: 0.205619
Epoch 1500/2000 Cost: 0.204522
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202485
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200635
Epoch 2000/2000 Cost: 0.199769


In [30]:
# test the model with a random input of [73, 80, 75]
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)               # forward calculation
print('prediction when input = [73, 80, 75]:', pred_y)

prediction when input = [73, 80, 75]: tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [31]:
# check the parameters of the model
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


## Reference
https://pytorch.org/docs/stable/nn.html

https://tutorials.pytorch.kr/beginner/pytorch_with_examples.html#tensorflow-static-graph

https://www.geeksforgeeks.org/linear-regression-using-pytorch/

https://www.yceffort.kr/2019/02/19/pytorch-02-linear-regression/