In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Linear regression with PyTorch

In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)  # fix the random seed

x_train = torch.FloatTensor([[1],[2],[3]])  # x_train
y_train = torch.FloatTensor([[2],[4],[6]])  # y_train

In [12]:
# initialize weight W
W = torch.zeros(1, requires_grad=True) # W is initialized to zero, requires_grad=True allows W to change as the model learns
print(W)

tensor([0.], requires_grad=True)


In [13]:
# initialize bias b
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [14]:
# hypothesis
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [15]:
# cost function
cost = torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [16]:
# optimizer (stochastic gradient descent)
optimizer = optim.SGD([W, b], lr=0.01)

optimizer.zero_grad()    # initialize the gradient to zero

cost.backward()          # calculate the gradient by differentiating the cost function

optimizer.step()         # update W and b

In [17]:
# train the model
nb_epochs = 1999    # set epochs

for epoch in range(nb_epochs + 1):
  # calculate H(x)
  hypothesis = x_train * W + b

  # calculate cost
  cost = torch.mean((hypothesis - y_train)**2)

  # update H(x) using cost
  optimizer.zero_grad()    # initialize the gradient to zero
  cost.backward()          # calculate the gradient by differentiating the cost function
  optimizer.step()         # update W and b

  # print log every 100 epoch
  if epoch % 100 == 0:
    print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, W.item(), b.item(), cost.item()))

Epoch    0/1999 W: 0.353, b: 0.151 Cost: 14.770963
Epoch  100/1999 W: 1.746, b: 0.577 Cost: 0.047939
Epoch  200/1999 W: 1.801, b: 0.453 Cost: 0.029624
Epoch  300/1999 W: 1.843, b: 0.356 Cost: 0.018306
Epoch  400/1999 W: 1.877, b: 0.280 Cost: 0.011312
Epoch  500/1999 W: 1.903, b: 0.220 Cost: 0.006990
Epoch  600/1999 W: 1.924, b: 0.173 Cost: 0.004319
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002669
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001649
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001019
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000630
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000389
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000240
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008