In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Tensor manipulation

## View

It changes the shape of tensors while retaining the number of elements. It is similar to "Reshape" in NumPy.

In [8]:

import numpy as np
import torch

t = np.array([[[0,1,2],
                [3,4,5]],
               [[6,7,8],
                [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft)
print(ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]])
torch.Size([2, 2, 3])


In [9]:
# change the shape with "view"
print(ft.view([-1,3]))       # change the shape of the tensor to (?,3)
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [10]:
print(ft.view([-1,1,3]))    # change the shape of the tensor to (?,1,3)
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze, Unsqueeze
"squeeze" eliminates the dimension when it's 1. "unsqueeze" is the opposite operation to "squeeze".

In [16]:
print(ft.view([4,1,3]))
print(ft.view([4,1,3]).shape)
print(ft.view([4,1,3]).squeeze())
print(ft.view([4,1,3]).squeeze().shape)  # 2nd dimension is eliminated, leading to the tensor of 2-dimension

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [24]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.]],

         [[ 6.,  7.,  8.],
          [ 9., 10., 11.]]]])
torch.Size([1, 2, 2, 3])


## Tensor type casting

https://pytorch.org/docs/stable/tensors.html

In [26]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [28]:
print(lt.float()) # to float

tensor([1., 2., 3., 4.])


In [29]:
bt = torch.ByteTensor([True, False, True, False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [30]:
print(bt.long())   # to long
print(bt.float())  # to float

tensor([1, 0, 1, 0])
tensor([1., 0., 1., 0.])


## Concatenate (cat, stack)

In [31]:
x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])
print(x)
print(y)

tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])


In [32]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x,y], dim=0).shape)
print(torch.cat([x,y], dim=1))
print(torch.cat([x,y], dim=1).shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
torch.Size([4, 2])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])
torch.Size([2, 4])


In [38]:
print(torch.stack([x,y]))
print(torch.stack([x,y]).shape)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
torch.Size([2, 2, 2])


In [36]:
print(torch.stack([x,y], dim=1))
print(torch.stack([x,y]).shape)

tensor([[[1., 2.],
         [5., 6.]],

        [[3., 4.],
         [7., 8.]]])
torch.Size([2, 2, 2])


## Ones_like and zeros_like

In [39]:
z = torch.FloatTensor([[0,1,2], [2,1,0]])
print(z)
print(z.shape)

tensor([[0., 1., 2.],
        [2., 1., 0.]])
torch.Size([2, 3])


In [40]:
print(torch.ones_like(z))   # tensor filled with 1 in the same size of z

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [41]:
print(torch.zeros_like(z))  # tensor filled with 0 in the same size of z

tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place operation

In [43]:
print(x.mul(2.))
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


In [45]:
print(x.mul_(2.))  # in-place operation by adding "_" after "mul"
print(x)

tensor([[ 4.,  8.],
        [12., 16.]])
tensor([[ 4.,  8.],
        [12., 16.]])
