In [24]:
!pwd

/content


In [25]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# What is tensor?

Tensor is a generalized array of numbers, such as vector (1d), matrix (2d), and tensors (more than 3d).

# Numpy array vs. PyTorch tensor

## 1D array with Numpy

In [26]:
import numpy as np

t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t1)

[0. 1. 2. 3. 4. 5. 6.]


In [27]:
print('Rank of t1: ', t1.ndim)   # rank
print('Shape of t1: ', t1.shape) # shape

Rank of t1:  1
Shape of t1:  (7,)


## 2D array with Numpy

In [28]:
t2 = np.array([[1.,2.,3.], [4.,5.,6.], [7.,8.,9.], [10.,11.,12.]])
print(t2)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [29]:
print('Rank of t2: ', t2.ndim)
print('Shape of t2: ', t2.shape)

Rank of t2:  2
Shape of t2:  (4, 3)


## 1D array with PyTorch

In [30]:
import torch
print(torch.__version__)

2.1.0+cu118


In [31]:
t3 = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t3)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [32]:
print(t3.dim())   # rank
print(t3.shape)   # shape
print(t3.size())  # shape

1
torch.Size([7])
torch.Size([7])


In [33]:
# indexing and slicing
print(t3[0], t3[1], t3[-1])
print(t3[2:5], t3[4:-1])
print(t3[:2], t3[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


## 2D array with PyTorch

In [34]:
t4 = torch.FloatTensor([[1.,2.,3.],
                        [4.,5.,6.],
                        [7.,8.,9.],
                        [10.,11.,12.]])
print(t4)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [35]:
print(t4.dim())
print(t4.size())

2
torch.Size([4, 3])


In [36]:
print(t4[:, 1])
print(t4[:, 1].size())

print(t4[:,:-1])

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


# Broadcasting

In [37]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1)
print(m2)
print(m1+m2)

tensor([[3., 3.]])
tensor([[2., 2.]])
tensor([[5., 5.]])


In [38]:
m3 = torch.FloatTensor([[1,2]])
m4 = torch.FloatTensor([[3],[4]])
print(m3.size())
print(m4.size())
print(m3+m4)

torch.Size([1, 2])
torch.Size([2, 1])
tensor([[4., 5.],
        [5., 6.]])


Users should be very careful when they use Broadcasting since it would be hard to track and debug.

# Matrix multiplication vs. Element-wise multiplication

In [41]:
m5 = torch.FloatTensor([[1,2],[3,4]])
m6 = torch.FloatTensor([[1],[2]])

print(m5.matmul(m6))  # matrix multiplication
print(m5@m6)          # matrix multiplication

tensor([[ 5.],
        [11.]])
tensor([[ 5.],
        [11.]])


In [45]:
print(m5 * m6)     # element-wise multiplication
print(m5.mul(m6))  # element-wise multiplication

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


Broadcasting was performed, followed by element-wise multiplication of m5 and m6.

# Mean

In [48]:
print(m5)
print(m5.mean())       # total mean of m5
print(m5.mean(dim=0))  # mean of the columns

tensor([[1., 2.],
        [3., 4.]])
tensor(2.5000)
tensor([2., 3.])


dim=0 means it eliminates the first dimension of the tensor. That is, only column (dim=1) is retained in this case.

In [49]:
print(m5.mean(dim=1))  # mean of the rows

tensor([1.5000, 3.5000])


In [50]:
print(m5.mean(dim=-1))  # mean of the rows

tensor([1.5000, 3.5000])


# Sum

In [51]:
print(m5.sum())
print(m5.sum(dim=0))
print(m5.sum(dim=1))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])


# Max & ArgMax

In [53]:
print(m5.max())
print(m5.max(dim=0))

tensor(4.)
torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


In [54]:
print(m5.max(dim=1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
