In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# 1. Mini batch and batch size

In [15]:
import torch

x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

While the example data set only contains five samples, there is a lot more data (e.g., millions) to deal with in real-world projects. Therefore, in many cases, training with the entire data set would be computationally too intensive or implausible.  
**Mini-batch** is a subset of the training data used in each iteration of the optimization algorithm.

![picture](https://wikidocs.net/images/page/55580/%EB%AF%B8%EB%8B%88%EB%B0%B0%EC%B9%98.PNG)

**Epoch**: one complete pass through the entire training dataset  
**Batch size**: size of the mini-batch  
**Minibatch Gradient Descent**: Gradient descent method performed by mini-batch unit

# 2. Iteration

**Iteration** is the number of updating parameters (that is, weight and bias) in one epoch.

![picture](https://wikidocs.net/images/page/36033/batchandepochiteration.PNG)


# 3. Data load

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# import TensorDataset and DataLoader
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [17]:
# train data
x_train  =  torch.FloatTensor([[73,  80,  75],
                               [93,  88,  93],
                               [89,  91,  90],
                               [96,  98,  100],
                               [73,  66,  70]])
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

**TensorDatset** takes tensors as input and transforms them into a data set.

In [18]:
# save the train data to "dataset" object
dataset = TensorDataset(x_train, y_train)

**DataLoader** has two parameters: data set and mini-batch size. Mini-bach size is normally multiple of two.

In [19]:
# save the data set and mini-batch information to "dataloader" object
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [20]:
# initiate the model and optimizer
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [21]:
for batch_idx, samples in enumerate(dataloader):
  print(samples[0])

tensor([[89., 91., 90.],
        [73., 80., 75.]])
tensor([[ 93.,  88.,  93.],
        [ 96.,  98., 100.]])
tensor([[73., 66., 70.]])


In [22]:
# train the model
nb_epochs = 20

for epoch in range(nb_epochs + 1):
  # check how mini-batch concepts work
  for batch_idx, samples in enumerate(dataloader):
    print(batch_idx)
    print(samples)

    x_train, y_train = samples    # divide samples into x_train and y_train

    # H(x)
    prediction = model(x_train)   # same as model.forward(x_train)

    # cost calculation
    cost = F.mse_loss(prediction, y_train)

    # update H(x) using cost
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

0
[tensor([[ 73.,  80.,  75.],
        [ 96.,  98., 100.]]), tensor([[152.],
        [196.]])]
Epoch    0/20 Batch 1/3 Cost: 17060.908203
1
[tensor([[89., 91., 90.],
        [93., 88., 93.]]), tensor([[180.],
        [185.]])]
Epoch    0/20 Batch 2/3 Cost: 5171.281250
2
[tensor([[73., 66., 70.]]), tensor([[142.]])]
Epoch    0/20 Batch 3/3 Cost: 771.635071
0
[tensor([[73., 66., 70.],
        [89., 91., 90.]]), tensor([[142.],
        [180.]])]
Epoch    1/20 Batch 1/3 Cost: 526.245911
1
[tensor([[ 96.,  98., 100.],
        [ 73.,  80.,  75.]]), tensor([[196.],
        [152.]])]
Epoch    1/20 Batch 2/3 Cost: 261.398132
2
[tensor([[93., 88., 93.]]), tensor([[185.]])]
Epoch    1/20 Batch 3/3 Cost: 66.357750
0
[tensor([[ 93.,  88.,  93.],
        [ 96.,  98., 100.]]), tensor([[185.],
        [196.]])]
Epoch    2/20 Batch 1/3 Cost: 17.800320
1
[tensor([[73., 66., 70.],
        [89., 91., 90.]]), tensor([[142.],
        [180.]])]
Epoch    2/20 Batch 2/3 Cost: 2.820609
2
[tensor([[73., 80., 75.

In [23]:
# random input: [73, 80, 75]
new_var =  torch.FloatTensor([[73, 80, 75]])
# get prediction for the random input above
pred_y = model(new_var)
print("prediction for [73, 80, 75]:", pred_y)

prediction for [73, 80, 75]: tensor([[150.2217]], grad_fn=<AddmmBackward0>)
